server:
  port: 8080


spring:
  jmx:
    enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_inserts: true
        order_update: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  quartz:
    properties:
      org.quartz.threadPool:
        threadCount: 2